spring.application.name=skillhubapi

#Alteração de porta
#server.port=8081

application.title = Minha API
application.version = 1.0

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/skillhub
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto PostgreSql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
